bind_addr = ":8080"
logger_level = "debug"
secret_key = "your_mom"
default_role_id = 2
unauthorized_id = 0
servers = ["localhost:8000/api/v3","localhost:8080/api/v3"]

[storage]
database_uri = "host=localhost port=5432 user=postgres password=lthgfhjkm dbname=Users sslmode=disable"